### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#13]
### Value Proposition

**As a** user **I need** to see a header and footer
**to be able to** have an idea where a navigation will be, once its finished in a later user story.

### Description

![2022-11-30 userstory_headerandlogin](https://user-images.githubusercontent.com/43116175/204803941-cfb7060b-5a55-4d78-82ea-34bc472c7f8d.svg)

### Acceptance Criteria

- [x] I visit the website and see a header and a footer
- [x] the footer displays: back to the top
- [x] the header displays a logo as well as the name 'contacto'

### Tasks

(for developers team)

- [x] create component: header
- [x] create component: footer
- [x] implement logic for back to the top button on footer component
- [x] implement svg logo and contacto text on the header component
- [x] put both new components into _app.js

### Sizing/Complexity

**S **
