### ISSUE TITLE
Login to see contacts

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#2]
### Value Proposition

**As a** User **I need** to login
**to be able to** see my contacts.

### Description

I type in my name and login with my user name and can see my contacts.

![2022-11-27 userstory_login_to_see_contacts](https://user-images.githubusercontent.com/43116175/204254043-947d9fde-0ed7-4d6a-aeda-4a5c7033309d.svg)
![2022-11-27 userstory_login_to_see_contact_mycontacts](https://user-images.githubusercontent.com/43116175/204129679-2744c6db-29ac-497c-9f0c-dd6d2bfed114.svg)

### Acceptance Criteria

- [x] I can type my name into an input field
- [x] I can push the login button 
- [x] when the loading is done, I can see a dummy my contacts page

### Tasks
(for developers team)

- [x] implement login with static route to myContacts (heading, input, login button)
- [x] implement moduleContact module for jsx structure of single contact card
- [x] implement dummy data in my contacts page
- [x] implement useState variable to pass logged in user details to my contacts
- [x] implement useState for later use as database array with objects
- [x] implement design

### Sizing/Complexity

** M**
