### ISSUE TITLE
Button: Send mail

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#24]
### Value Proposition

**As a**  logged in User **I need** to push send mail button
**to be able to** send an email with the system stand mail program.

### Description

![2022-12-07 userstory_button_2_send](https://user-images.githubusercontent.com/43116175/206146684-81694b8b-35f5-4108-b5d8-57f5f2138903.svg)

### Acceptance Criteria

- [x] I push the mail button on a single contact
- [x] My standard email program opens up

### Tasks

(for developers team)

- [x] implement button in pages/singleProfile
- [x] implement onClick to open sendmail

### Sizing/Complexity

**S **
