### ISSUE TITLE
Button: Call contact

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#25]
### Value Proposition

**As a** logged in User **I need** push the button call
**to be able to** call my contact, if a VoIP software is properly configured.

### Description

![2022-12-07 userstory_button_3_call](https://user-images.githubusercontent.com/43116175/206147336-674061df-540e-4109-b512-7d5d61ee44d5.svg)

### Acceptance Criteria

- [x] I push call button
- [x] VoIP software opens (e.g. mobile phone telephone)

### Tasks

(for developers team)

- [x] implement button in pages/singleProfile
- [x] onClick to open VoIP software

### Sizing/Complexity

** S **
