### ISSUE TITLE
Button: open website

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#26]
### Value Proposition

**As a**  logged in User  **I need** to push open website
**to be able to** open the website of my contact.

### Description

![2022-12-07 userstory_button_4_open](https://user-images.githubusercontent.com/43116175/206148109-a76f6d7b-16e4-49db-9086-8e25b52e3946.svg)

### Acceptance Criteria

- [x] I push the button open in a single profile
- [x] a website opens in new tab

### Tasks

(for developers team)

- [x] implement button in pages/singleProfile
- [x] clicking opens new tab with website

### Sizing/Complexity

** S **
