### ISSUE TITLE
MongoDB: Implement User Login (advanced)

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#31]
### Value Proposition

**As a** user **I need** to push login
**to be able to** login into the application.

### Description

![2022-11-27 userstory_login_to_see_contacts](https://user-images.githubusercontent.com/43116175/206448882-51d9a687-65aa-43cb-9c8e-520d46fc1575.svg)

### Acceptance Criteria

- [ ] I push login
- [ ] I get logged in

### Tasks

(for developers team)

- [ ] Implement backend api with postman
- [ ] do first tests for GET requests
- [ ] implement user object with login data
- [ ] fetch database data in index.js (Login page) and compare

### Sizing/Complexity

** L**
