### ISSUE TITLE
MongoDB: Implement 'My Contacts' (advanced)

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#32]
### Value Proposition

**As a** logged in User **I need** login
**to be able to** see my contacts.

### Description

![2022-11-27 userstory_login_to_see_contact_mycontacts](https://user-images.githubusercontent.com/43116175/206450733-172b2184-69ab-442c-8116-626965f64728.svg)

### Acceptance Criteria

- [ ] I log into the app
- [ ] I see my contacts

### Tasks

(for developers team)

- [ ] implement user on database
- [ ] show in view

### Sizing/Complexity

** M **
