### ISSUE TITLE
Edit own profile

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#33]
### Value Proposition

**As a** logged in User **I need** to click on edit in my profile
**to be able to** edit my own information.

### Description

![2022-12-08 userstory_ownprofile_edit](https://user-images.githubusercontent.com/43116175/206459888-b258146d-4525-4a14-b688-ddf7cabea932.svg)

### Acceptance Criteria

- [x] i click on update in my own profile
- [x] i can edit my information
- [x] the update button saves the information

### Tasks

(for developers team)

- [x] implement rewrite of array of objects in own profile with new information
- [x] implement button for udate
- [x] update: updates array information

### Sizing/Complexity

** M **
