### ISSUE TITLE
Edit user profiles

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#34]
### Value Proposition

**As a** logged in User **I need** to click on edit
**to be able to** edit my contacts information.

### Description

![2022-12-08 userstory_ownprofile_edit](https://user-images.githubusercontent.com/43116175/206460340-022a065a-ca7b-4645-9483-a9ea86c2dda6.svg)

### Acceptance Criteria

- [x] i click on a single profile in my contacts
- [x] single profile shows up
- [x] i click on update
- [x] i can update information and save it

### Tasks

(for developers team)

- [x] implement rewrite of array of objects in users profile with new information
- [x] implement button for rewrite logic
- [x] update: saves all data to array

### Sizing/Complexity

**  M **
