### ISSUE TITLE
MongoDB: Implement 'Myself' (advanced)

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#35]
### Value Proposition

**As a** logged in User **I need** to visit my profile
**to be able to** see my information and edit it.

### Description

![2022-12-08 userstory_ownprofile_edit](https://user-images.githubusercontent.com/43116175/206461198-c0d8469f-d86f-4828-8f52-b1254d42a02d.svg)

### Acceptance Criteria

- [ ] I can click on Myself in the navbar
- [ ] I see my profile and can edit my information

### Tasks

(for developers team)

- [ ] implement database logic in myself

### Sizing/Complexity

**S **
