### ISSUE TITLE
MongoDB: Implement 'Add Contact' (advanced)

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#36]
### Value Proposition

**As a** logged in User **I need** to click on the navbar 'Add Contact'
**to be able to** add a contact.

### Description

![2022-11-27 userstory_addcontact](https://user-images.githubusercontent.com/43116175/206461497-54602b2c-8f32-4949-a474-a44c8d248bf0.svg)

### Acceptance Criteria

- [ ] I can click on 'Add Contact' in the navbar
- [ ] I see an add contact mask
- [ ] I can save a new contact

### Tasks

(for developers team)

- [ ] implement 'Add Contact' into database logic

### Sizing/Complexity

**S **
