### ISSUE TITLE
MongoDB: Implement 'Single Contact' (advanced)

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#37]
### Value Proposition

**As a** logged in User **I need** to open a single contact from the my contacts dashboard
**to be able to** view and edit it, as well as access all functions (route, call, ... )

### Description

![2022-12-07 userstory_button_1_route](https://user-images.githubusercontent.com/43116175/206464103-15903397-c833-4a5a-91b8-3d655b67846c.svg)
![2022-12-07 userstory_button_2_send](https://user-images.githubusercontent.com/43116175/206464106-c79bd72d-eef6-40a5-8212-85f0570f4ad3.svg)
![2022-12-07 userstory_button_3_call](https://user-images.githubusercontent.com/43116175/206464107-8f73b724-72a5-487e-b862-052ff4e74676.svg)
![2022-12-07 userstory_button_4_open](https://user-images.githubusercontent.com/43116175/206464108-3d1eee00-8224-4b08-94d7-32caabf6cc90.svg)

### Acceptance Criteria

- [ ] i can click on a single profile in my contacts dashboard
- [ ] i can use all functions as well as edit the contact

### Tasks

(for developers team)

- [ ] refactor logic to database

### Sizing/Complexity

** M **
