### ISSUE TITLE
MongoDB: Implement 'Register' (advanced)

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#39]
### Value Proposition

**As a** logged in User...) **I need** ...(describe the goal)
**to be able to** ...(describe the reason)

### Description

![2022-12-08 userstory_register](https://user-images.githubusercontent.com/43116175/206465677-501d1bcc-b1eb-42fc-94ff-5783de53400a.svg)

### Acceptance Criteria

- [ ] on visiting the site I get two options
- [ ] register and login
- [ ] i can register to create an account

### Tasks

(for developers team)

- [ ] implement register form
- [ ] save to database

### Sizing/Complexity

** L**
