### ISSUE TITLE
Own profile from burger menu

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#4]
### Value Proposition

**As a** logged in User **I need** to click on own profile 
**to be able to** see my own profile.

### Description

![userstory_own_profile_from_burger_menu](https://user-images.githubusercontent.com/43116175/204130123-f6994f22-1ee5-45e9-99f8-02bc665329c9.svg)

### Acceptance Criteria

- [x] i am able to click on own profile in burger menu
- [x] when the click is done im directed to my own profile page

### Tasks

(for developers team)

- [x] implement static route to own profile
- [x] own profile is in pages folder of nextjs
- [x] all information for picture frame, name and personal information is provided by _db array

### Sizing/Complexity

**S *
