### ISSUE TITLE
Local Storage: save all contacts persistent

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#45]
### Value Proposition

**As a** logged in User **I need** to have a persistent storage
**to be able to** see my contacts once I close the website.

### Description

There is nothing visible for the user.

### Acceptance Criteria

- [x] I close the website
- [x] when I reopen the website my added and edited contacts still exist

### Tasks

(for developers team)

- [x] implement local storage
- [x] rewrite page logic: login, myContacts, singleProfile, myProfile
- [x] clean up dbArray logic

### Sizing/Complexity

** L**
