### ISSUE TITLE
Upload pictures to cloudinary

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#49]
### Value Proposition

**As a** user **I need** to upload my picture
**to be able to** see them in every profile (own, contact and new user).

### Description

The previously displayed image can now be choosen yourself from an image upload from your PC.

### Acceptance Criteria

- [x] My profile: I click on upload and can upload an image that upon submit is saved
- [x] Contact profile: I click on upload and can upload an image that upon submit is saved
- [x] Add user: I upload an image and click on submit and the new user displays the image

### Tasks

(for developers team)

- [x] use cloudinary documentation to implement the image upload logic

### Sizing/Complexity

** L**
