### ISSUE TITLE
Clickable profile in myContacts

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#5]
### Value Proposition

**As a** logged in User **I need** to click on my contact cards
**to be able to** see a single profile page.

### Description

![2022-11-27 userstory_login_to_see_contact_mycontacts](https://user-images.githubusercontent.com/43116175/204130368-d5f12229-621e-4936-87bd-7e244e7d2196.svg)
Clicked on single contact ... 
![2022-11-27 userstory_clickable_profiles](https://user-images.githubusercontent.com/43116175/204130386-e4d6610d-cb91-42e3-8c4a-8674e7b2bbac.svg)

### Acceptance Criteria

- [x] I can click on a single profile in myContacts
- [x] when loading is finished I can see a single profile page

### Tasks

(for developers team)

- [x] implement a clickable profile in my contacts
- [x] implement new page 'singleProfile'
- [x] onClick to write useState name for showing a single profile page in mycontacts
- [x] implement singleprofile page

### Sizing/Complexity

** M **
