### ISSUE TITLE
Delete Single Contact

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#50]
### Value Proposition

**As a** user **I need** to click delete
**to be able to** delete a contact.

### Description

![test_github](https://user-images.githubusercontent.com/43116175/210177881-cbcd0275-0144-45c8-b601-cf6cde01837c.jpg)

### Acceptance Criteria

- [x] I can click on a single user in contact dashboard
- [x] in the single user view,  I can click delete to get rid of the user

### Tasks

(for developers team)

- [x] implement local storage delete option in single profile view

### Sizing/Complexity

**S **
