### ISSUE TITLE
Add a new contact

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#6]
### Value Proposition

**As a** logged in User **I need** to click on add contact in the burger menu
**to be able to** reach the add contact page to add a new contact.

### Description

![2022-11-27 userstory_addcontact](https://user-images.githubusercontent.com/43116175/204131570-961943b2-5796-4268-8d52-6e63d2d92bde.svg)

### Acceptance Criteria

- [x] I click on add contact in the burger menu
- [x] I can add a contact to the contact list, which is displayed in my contacts page

### Tasks

(for developers team)

- [x] implement new static route in pages
- [x] addContact should display a form that makes it possible to add a contact to the contacts array

### Sizing/Complexity

** M **
