### ISSUE TITLE
burger menu logout button

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#7]
### Value Proposition

**As a**  logged in User **I need** to click on logout in the burger menu
**to be able to** get logged out.

### Description

![2022-11-27 userstory_burger_menu_logout](https://user-images.githubusercontent.com/43116175/204131799-557f83f3-048b-4d44-9d17-d680a42eda5e.svg)

### Acceptance Criteria

- [x] I click on logout in burger menu
- [x] i get logged out and see login page

### Tasks

(for developers team)

- [x]  put Link on logout button in menu
- [x] redirect to login page

### Sizing/Complexity

**S **
