### ISSUE TITLE
Search bar for my contacts

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#8]
### Value Proposition

**As a** logged in User **I need** to type something in my contacts into the search bar
**to be able to** search through the names of contacts.

### Description

![2022-11-27 userstory_searchbar](https://user-images.githubusercontent.com/43116175/204131923-8154c3f2-c022-4ec5-a2c0-86c9487df0c0.svg)

### Acceptance Criteria

- [x] I'm in my contacts
- [x] i can type into searchbar
- [x] search bar delivers results of names

### Tasks

(for developers team)

- [x] implement search function in myContacts
- [x] implement onChange Listener
- [x] implement corresponding function
- [x] write simple search (keyword case sensitive)
- [x] write complex search (keyword case insensitive and live)

### Sizing/Complexity

** M**

**Comment by Justus-Becker-Rabbenstein** [comment]
Updated Tasks for developers after gathering enough information to understand the implementation process of a search bar.
