### ISSUE TITLE
My contacts page

### ISSUE THREAD

**Issue by Justus-Becker-Rabbenstein** [Justus-Becker-Rabbenstein/contacto#9]
### Value Proposition

**As a** logged in User **I need** to arrive at my contacts page
**to be able to** see my contacts

### Description

![2022-11-27 userstory_login_to_see_contact_mycontacts](https://user-images.githubusercontent.com/43116175/204254609-7213fc1b-fc7c-4614-a524-bc8ea3e0e2c3.svg)

### Acceptance Criteria

- [x] I can see contact cards that show a name, an address, an e-mail, a phone number as well as a website

### Tasks

(for developers team)

- [x] create site: pages/myContacts/index.js
- [x] implement db array with dummy data in pages/_db/dbarray.js
- [x] import dbarray.js in myContacts/index.js
- [x] use the array method map in myContacts to map over the provided data from dbarray.js and the layout from the single contact js
- [x] design the displayed single cards to look like one card with the single contact component

### Sizing/Complexity

** M **

**Comment by SirJohn42Walker** [comment]
I think, and that is totally my personal preference, so you do you, that an M should probably contain a few more checkboxes for the developers, so that you can check one of more often and not only at the end of the whole process. Asides from that: Looks great!

**Comment by Justus-Becker-Rabbenstein** [comment]
> I think, and that is totally my personal preference, so you do you, that an M should probably contain a few more checkboxes for the developers, so that you can check one of more often and not only at the end of the whole process. Asides from that: Looks great!

Dear SirJohn42Walker,
thank you indeed for the quite sophisticated improvement ideas.
As you may have seen by now I put your improvement efforts into practise and built a better user story.
Thank you very much and
yours sincerly
Justus
